@server = http://localhost:8080
@productos = {{server}}/api/productos
@ventas = {{server}}/api/ventaDetalles
###
GET {{ventas}}
###
POST {{productos}}
Content-Type: application/json

{
    "nombre": "Quena",
    "categoria": "Viento",

}
###
POST {{ventas}}
Content-Type: application/json

{"nombre": "Otro Producto"}
###
GET {{server}}/api/productos/1/productos
###
GET {{server}}/api/ventas/1/ventas